/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: lib/theme/musicTheme.ts
 * Command: astryx theme build lib/theme/musicTheme.ts --out lib/theme/music-theme.css
 * Generated: 2026-09-22T04:17:32.309Z
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
import type { IconRegistry } from '@astryxdesign/core/Icon';
export declare const matchaIconRegistry: IconRegistry;
export declare const musicTheme: DefinedTheme;
