name: Deploy to Sevalla

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Sevalla Deploy
        run: |
          curl -X POST "${{ secrets.SEVALLA_DEPLOY_HOOK }}"

